spring:
  threads:
    virtual:
      enabled: true
  application:
    name: management-backend
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1}
    driver-class-name: ${SPRING_DATASOURCE_DRIVER_CLASS_NAME:org.h2.Driver}
    username: ${SPRING_DATASOURCE_USERNAME:sa}
    password: ${SPRING_DATASOURCE_PASSWORD:}
  h2:
    console:
      enabled: true
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true

springdoc:
  swagger-ui:
    path: /api-docs-ui
  api-docs:
    path: /v3/api-docs
