sudo: required
dist: trusty
language: node_js
node_js:
  - '10.16.3'
services:
  - docker

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

env:
  global:
    - secure: "JvVsC1TVa1FlMtHNLio5FlMSZhemGEFechMeP77tc0xCq2lSlPirrragKF5saC1CCe9MDDx9gQnA6FCydHLhDYGMsT1lPeVZWHgd3/Imf8gKM/baNxSK9rjlafQsW2lxnFsouW8/LKoFQLQvbM7oFEizTbKwbFQCYbLaSY1G6aVqHtrYqZaBF5SIcL9b6Jv0W/9kHeji5HEgS9d+fj93Zkk9Y18jvOTuOJAEUm//VxgL/kv8lpcPcR9I9TJxEPL0hBeozTHANwtWAI/ES5Gue10QcNwxWehybR98j/vyE1wRwFkrEt2sJpv62Lz7/rKvpj+CTpE2Oxyr5o3TrkhodhitVtZ8EIME41ylru1VOD2mVtlpfUE95tPICtaZgbnJub/ucAVYPCdRfd2jwxZ4RNGIRZBKLFI3CyzBMXxtJyTrZpcjjo3XMkIGdORo5iX6mKIotGmz1KczWIYGMTJGcOAOAQus2FGUwRvXsxgr6OnTFJv61OdZ1L5cY7c9NaLBnhdQzl914627DlCZdIHBb/l8unYaloRNfZRednRZAbL1bK+2235pB3DIuQkX5XXzi4YFG+Lv70NiqDNjSGLAx8oU5qmJFH7M9aJ8T4j7ToHG0ahIE/mT1+18GG8h2ayulWu4MnZvWxVQ/4ph16VQiFeVLAeYnUmpI1kieBGZjdw="
    - secure: "rQt7RAw1QT05D1xMsve2VeCeABr2SWtEaHVaZo5kH3yLzLviFOgMDC7Wx2rTq+qdvhuqJ3H+Xxg9jPXygmmZ5h/D9fFtiH08d7JNoaKQolYmR5tExn40Hjnse2uVlHpfuaEmQXpt3gNoHTNvM5kopw5eIAtZl951JvzoCwHN9x2P7pDWNBpYJ5vunenGrhpwxBm/Lu+AsV5zKPMs1RXIPM0nkWIqZ5n+EJf89Q7PUQ3gc7PDhsnKEbB1f5deJrzQNm3rh32egScpOUv0Cv9Wvq5GoQdEQr5LUCqxFLVmUEtR4Yk528mO3Ch1rwQBB+GcLxdJdQcvaHD9e8b8rFIk9MiGHe94+1VwvLsPWX00XTFcujXdY+ZeUGyYTYcjlTbQpDFJgu/x2vFToH9JRy46cHLIJ2K7tiqKKmaIfkbn8Hy7xzFu4pg5M3x1SNTgITsGwbt/BRXT6ZZHmh+pBqqne0gxS4T2wuh6P7jYr+3ZzxZnvmPBH84UCo+z0frdjwpV2Vj3StKGAyj2XS6hSKTLN6mC8bt/PU80qgd7sjYTcOEyZ5IBMheGRiK2XtjbM15SaTYI4zCn0xqg4O/Skblw/o3OWCiNdWBFLkf0SrUoBqIlrjD+PsFrJA4YvajP4ZlZhIBtrEKfhMOcEFicsryW88Z/x7o3z81XJucY07tuYKA="
    - COMMIT=${TRAVIS_COMMIT::7}
    - IMAGE_NAME=tabletennistournament/match-management-client

before_install:
  - docker pull bitnami/nginx:1.16
#  - export CHROME_BIN=chromium-browser
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI

after_success:
  - export TAG=`if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH-$COMMIT"; fi`
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker build . -t $IMAGE_NAME:latest
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:latest
  - docker push $IMAGE_NAME:$TAG
  - export TITLE="$IMAGE_NAME:$TAG is built properly and pushed to Dockerhub"
  - export TIMESTAMP=`date`
  - export GIT_LOG=`git log -1 --pretty=%B $COMMIT`
  - export TEXT="[build version] $TAG<br />[datetime] $TIMESTAMP<br />[changelog] $GIT_LOG<br />"


