sudo: required
dist: trusty
language: node_js
node_js:
  - '10.16.3'
services:
  - docker
matrix:
  fast_finish: true

addons:
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable

cache:
  directories:
    - ./node_modules

env:
  global:
    - secure: "U4onCmRz9xpGjr27VO/TqDU/Lu75rRcw/s9kINYiJpDxay/pRm5cy3ZVJqquE4j4EsoT3KRQwkqfw8bx145zAFrJ8QRVWqTC2/MoAgaqzpWArR+moV0V8iQ/uEa1bDAVTWwx/2CdHS64rxpVD7w32NzC1PeyEc4nlnVADktoUzsZg2yd2XMo2GEc/MC2v3Hr4IN7CZoWiBD2XKxSwbSFJY1wugg1GCLj8ztYjERmI0BUzhYlLviCZlRY5RaSut4rJG6otdDSjnsJ9RiNcXujcSEFSnPW3RnvgBkUIro8aMdCC9KWkqdTf8H8yJekKAjUI5pWkcR9FCClzcMq7pBAlxPWiWAC38ffStoEM9it7eUp2EVnd8SrrE8AqLG1x53p5fXmbhXEvORkfah20CdqZ1Ad7epDR+c/b7PKWispaO0nEDpDcwyofMpnvU99Q+4BSoHHigeVf+M0t+ieGIagECrnsZKfYvAuubrWxV8wBoT/MFni8nVrU4dev9tcFqz2Lrg/2x7w9CcgCKuG6yiHVYZYaFR0NdGgxxVcdWylc99p4BgLMyiY5saAxb/GgrwJkh2iv8i3WyTtoPbO6Yuqud78v4ZvkQOORUL5yH/GYQxdYiX90kGeAv+T1oe0i6mz3rJBaJPlVSz0/KnjOzbM4l3YQIMD6ujCgFbHpc3YY8k="
    - secure: "Xd6mcg4GmVwg80kKof1qJIgbYbL588FnglpgozS+UXziOT7ShRtF3auEj7etPuv8ZW+9ncynodEsHuV8iKuEkxtRhSccRqPGIfnusNLJ78yEG1jhAm7gBGeZLynLK17lTxZmlQNLH3e6/4cHJEK0xT1F2x17PYN79sNr6OzxxO3qDECOWv5RFHKVGLCeYbjrSVsCnIuHDV5Epn/baaLiAerNbh1k/bkaIFJfz0/ukwGGTaI0yy7/zCoHOYnN1rLa+24UNCNBmPGCXmy+n7W0RddL9/ybHWOJjXpmnDY8UxFepKFgtrECqb2TSSlStSMdGQLAijCFI1r70gFrZ7IHE7PdC4dT+sAkJAHY/M+7U9ai2nPqddl2/n6cdA20wn5Ia58lFPKuq7N6ILQX5F/UdjEEbJnRNfPORmfvJvxvSFW0GkbT6D9lx5ITqH16VwQpGHAhf26q1hAyu05MGEVcNMzvJYnX3H/5wFV5dUrsb7QVo3IPqkVSc9v2J58dj/PmVSaL91Oa8rtGLT2Bgcv79catEXVy6YVQfV06i/EAun1BX7/am6G2EMYncmVPoMOle2eHGN7sc7RiL5bd/GrHFvf+DiBDCvpDaGM9vfcPey26F8itJpmGUircCk4D4YUxiw/DWtmqbPKIR3a0c8VXxvzQfJbGzVdNr/NYafn2omc="
   # CONFIG_REPOSITORY
    - secure: "E8Ja+SxO4xIGokWQTs4gCprc1t2g/+mWVu4qH707oDjX0nGkv+wytaFmwpdn2xXF1//wE5wNSz8SdBxyTNMQmyZq+jwOHtPnUFXjfxe+dTT+dnwT+h1jXDWLh1rtsGtqJJsAi9D87GZY5cqtMtevuqydnTLLKOiBX5j+3N5gpsl2b6xfkHlhs+Gwjl4VacSHHkWVIuABMlJKL9bAzdueqsza2H98cr4My3eW3gkMDOeyhX9+rmaagHpegkwUig2VNB1Gy2oLz3KAzIpOUIdsliG98vZM9dGXAdQqfqtHhQ/94eUoyFqfm9lUVIPr10hLe1xzRGiZRBOidTPvLgtfJTTJ9YQZjVksKqGlOZA632gxYMEWc0ZsdecQrMNJtvtbEksiOO0dsYv7eSI3teL4qSn7OPHqSzW+xSXQxj80aJ5u7cs97OIAih3o6CJC4UQHjCUgrt5vJKd+0NHgBuLvVUwzai8O4eJD1wbGCRvUd4VEgz7DDHehXAj+EWzvRCYvo0JRnvc+jrW5jy/saHWcnnBW5kgjgE/uzSYZbUBYzurMbg6NjSc/knyhn2YHux5olANAKMog14aM3PL20QzkpHZsFlAaaXibz0HJB+A69FHVdZ+aEzn/5SBNLPmRYQcfRttjLVrd2UscLAsGlEVdPK+9NLow7rHqdjMDdvobEDY="
    - APP_NAME=ttt-staging  
    - COMMIT=${TRAVIS_COMMIT::7}
    - IMAGE_NAME=tabletennistournament/match-management-client

before_install:
  - docker pull bitnami/nginx:1.16

install:
  - npm install

script:
  - npm run test -- --no-watch --no-progress --browsers=ChromeHeadlessCI
  - npm run build
  - export TAG=$(if [ ! -z "$TRAVIS_TAG" ]; then echo "$TRAVIS_TAG"; else echo "$TRAVIS_BRANCH-$COMMIT"; fi | sed 's/\//-/')
  - docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
  - docker build . -t $IMAGE_NAME:latest
  - if [ $TRAVIS_BRANCH == "master" ]; then docker tag $IMAGE_NAME:latest $IMAGE_NAME:master; fi
  - docker tag $IMAGE_NAME:latest $IMAGE_NAME:$TAG
  - docker push $IMAGE_NAME:latest
  - if [ $TRAVIS_BRANCH == "master" ]; then docker push $IMAGE_NAME:master; fi
  - docker push $IMAGE_NAME:$TAG
  - docker run -e APP_NAME=$APP_NAME -e CONFIG_REPOSITORY=$CONFIG_REPOSITORY -e YAML_PATH="app.frontend.image.tag" -e NEW_VALUE=$TAG tabletennistournament/gitops-deploy



