version: "3.3"  # optional since v1.27.0
services:
  mysql:
    image: holzleube/mysql-docker-image:5.2
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=ttv01
#    healthcheck:
#      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
#      timeout: 20s
#      retries: 10
  backend:
    image: holzleube/turniermanager:5.0
    ports:
      - "9000:9000"
    environment:
      - MYSQL_JDBC=jdbc:mysql://mysql:3306/tournamentManager
      - MYSQL_USER=root
      - MYSQL_PW=ttv01
      - WAIT_HOSTS=mysql:3306
      - WAIT_TIMEOUT=200
    depends_on:
      - "mysql"
  admin:
    image: holzleube/ttt-clients:2.0
    ports:
      - "80:8080"
    depends_on:
      - "backend"

