networks:
  app-tier:
    driver: bridge
services:
  mariadb:
    image: holzleube/mysql-docker-image:6.1
    ports:
      - "3306:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=ttv01
    networks:
      - app-tier
    healthcheck:
      test: ["CMD", "/opt/bitnami/scripts/mariadb/healthcheck.sh"]
      interval: 15s
      timeout: 5s
      retries: 6
      start_period: 30s
  backend:
    image: holzleube/turniermanager:5.4
    ports:
      - "9000:9000"
    environment:
      - MYSQL_JDBC=jdbc:mysql://mariadb:3306/tournamentManager
      - MYSQL_USER=root
      - MYSQL_PW=ttv01
    networks: 
      - app-tier
    depends_on:
      - "mariadb"
  admin:
    image: holzleube/ttt-clients:5.3.0-sunday
    ports:
      - "80:8080"
    networks:
      - app-tier
    depends_on:
      - "backend"

