apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    build: turnier-manager
  name: turnier-manager
spec:
  source:
    git:
      ref: master
      uri: 'https://gitlab.com/jonashansert/TurnierManager.git'
    type: Git
  strategy:
    jenkinsPipelineStrategy:
      jenkinsfilePath: Jenkinsfile
    type: JenkinsPipeline
  successfulBuildsHistoryLimit: 5