version: '3'
services:
  nginx:
    image: holzleube/tt-admin-view:5.0
    ports:
      - "80:8080"
    volumes:
      - ./my_server_block.conf:/opt/bitnami/nginx/conf/server_blocks/my_server_block.conf:ro
